obj-m := helloworld.o
helloworld-objs := hello_world.rust.o

CARGO ?= cargo
BUILD_MODE = release

export c_flags

$(src)/target/x86_64-unknown-none-linuxkernel/$(BUILD_MODE)/libhello_world.a: cargo_will_determine_dependencies
	cd $(src); $(CARGO) build -Z build-std=core,alloc --target=x86_64-unknown-none-linuxkernel --$(BUILD_MODE)

.PHONY: cargo_will_determine_dependencies

#%.rust.o: target/x86_64-unknown-none-linuxkernel/$(BUILD_MODE)/lib%.a
#	$(LD) -r -o $@ --whole-archive $<

%.rust.o: target/x86_64-unknown-none-linuxkernel/$(BUILD_MODE)/lib%.a
	$(LD) -r -e init_module -o $@ $<
